apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: pankajsingh8540/frontend:latest
        resources:
          limits:
            memory: "500Mi"   #500 megabytes
            cpu: "18m"       #1.0 or 1000m 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


