# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secret
# type: Opaque
# data:
#   postgres-root-password: MTIzNDU=


apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: root1234